ALTER TABLE team
DROP
FOREIGN KEY FK_TEAM_ON_TASKS;

ALTER TABLE team
DROP
FOREIGN KEY FK_TEAM_ON_USERS;

ALTER TABLE task
    ADD team_id INT NULL;

ALTER TABLE user
    ADD team_id INT NULL;

ALTER TABLE task
    ADD CONSTRAINT FK_TASK_ON_TEAM FOREIGN KEY (team_id) REFERENCES team (id);

ALTER TABLE user
    ADD CONSTRAINT FK_USER_ON_TEAM FOREIGN KEY (team_id) REFERENCES team (id);

ALTER TABLE team
DROP
COLUMN tasks;

ALTER TABLE team
DROP
COLUMN users;